name: altive_lints_workspace
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/altive_lints
  - packages/diffscrape

dev_dependencies:
  altive_lints:
    path: packages/altive_lints
  melos: ^7.3.0

melos:
  command:
    version:
      workspaceChangelog: false
