name: example
description: A example of altive_lints.
publish_to: none
version: 1.0.0
environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints:
    path: ../
  clock: ^1.1.2
