name: diffscrape
description: Diffscrape is a package for scraping and checking differences.
version: 0.0.1
publish_to: none
repository: https://github.com/altive/altive_lints

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  args: ^2.7.0
  html: ^0.15.6
  http: ^1.4.0

dev_dependencies:
  altive_lints:
    path: ../altive_lints
  test: ^1.26.2
